### ISSUE TITLE
Add `.gitignore` file

### ISSUE THREAD

**Issue by EitoZX** [code-chaser/dex#12]
A issue which is not related to discord bot, but more related to pushing files on github.
I noticed that there is no `.gitignore` file in your repository. I HIGHLY RECOMMEND you to add a `.gitignore` file (*Almost* all repositories have this file). Adding this file in your repository, stops tracking of the files added in that file. like for your repository, `__pycache__` one is suppose to be in the `gitignore`.
To learn more about `.gitignore`: https://git-scm.com/docs/gitignore
In case you want any reference, check: [.gitignore from one of my repository](https://github.com/EitoZX/Bank-Management-System/blob/master/.gitignore) (for learning purpose only)

Edit: Fixed typos lol

**Comment by code-chaser** [comment]
Fixed: added [`.gitignore`](https://github.com/code-chaser/dex/blob/main/.gitignore)

**Comment by EitoZX** [comment]
> Fixed: added [`.gitignore`](https://github.com/code-chaser/dex/blob/main/.gitignore)

GG
