### ISSUE TITLE
[BUG] - queue not clearing

### ISSUE THREAD

**Issue by prism-25** [code-chaser/dex#38]
## Bug Description
When we give command to the bot to leave the voice channel while it's playing something, it leaves the voice channel successfully, but the queue doesn't get cleared.

You can see this by using `$dex join` followed by `$dex queue`. It won't be empty.

## Steps to reproduce the behavior:
- Join a voice channel.
- Give the following commands to the bot (in order):
    -  `$dex playm Unstoppable by Sia; Closer; Shape of you;` - 3 songs in the queue
    - `$dex leave`
    - `$dex join`
    - `$dex queue` - shows a queue having those 3 songs

___

**_I believe that I can fix this, kindly assign me._**
___

**Comment by code-chaser** [comment]
Assigned!
You can start working on it!

**Comment by prism-25** [comment]
Thanks! 😄
