### ISSUE TITLE
[BUG] - `playm` command starts playing from second song

### ISSUE THREAD

**Issue by code-chaser** [code-chaser/dex#42]
## Explanation
When you queue multiple songs using `playm` command, it adds all of them to the queue but then while playing, skips the first one.

For example:
- using `playm s1; s2; s3; s4`
- queue: `s1 s2 s3 s4`
- first song played: `s2`

**Comment by aditi989** [comment]
I would like to work on this!

**Comment by code-chaser** [comment]
Assigned!
